spring.application.name=costumers.api

spring.datasource.url=jdbc:mysql://localhost:3306/onclinic_webapi?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=CenterRoomX77
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect